spring.application.name=greenlibrary

spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true

# JSP 사용 시 (Thymeleaf 미사용)
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# DB 설정 (Oracle 사용 시)
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:10.178.0.3:1521:xe
spring.datasource.username=system
spring.datasource.password=1234

# 파일 업로드
file.upload-dir=C:/upload/
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# MyBatis 설정
mybatis.mapper-locations=classpath:mybatis/mappers/*.xml
mybatis.type-aliases-package=com.example.greenlibrary

#연동테스트